image: "buildah/buildah"

variables:
  STORAGE_DRIVER: "vfs"
  BUILDAH_FORMAT: "docker"

before_script:
  - podman login -u $CI_USER -p $CI_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    #- podman pull $CI_REGISTRY_IMAGE:latest || true
    #- podman build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY/$CI_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_IMAGE:latest .
    - podman build -t $CI_REGISTRY/$CI_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY/$CI_IMAGE:latest .
    - podman push -q $CI_REGISTRY/$CI_IMAGE:$CI_COMMIT_SHA
    - podman push -q $CI_REGISTRY/$CI_IMAGE:latest

after_script:
  - podman logout $CI_REGISTRY