image: "buildah/buildah"

variables:
  NUMBER: 0
  STORAGE_DRIVER: "vfs"
  BUILDAH_FORMAT: "docker"

before_script:
  - export VERSION=$(git show -s --format=%ct $CI_COMMIT_SHA)
  #- export VERSION=$(date -d @$(git show -s --format=%ct $CI_COMMIT_SHA) +%y.%m).$NUMBER
  - podman login -u $CI_USER -p $CI_TOKEN registry.gitlab.com
  - podman login -u $GH_USER -p $GH_TOKEN docker.io

build:
  stage: build
  script:
    #- podman pull $CI_REGISTRY_IMAGE:latest || true
    #- podman build -f Containerfile --cache-from $CI_REGISTRY_IMAGE:latest -t registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA -t registry.gitlab.com/$CI_IMAGE:latest .
    - echo $VERSION

    - podman build -f Containerfile -t alertmanager-webhook-signal .

    - podman tag alertmanager-webhook-signal registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA
    - podman push -q registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA

    - podman tag alertmanager-webhook-signal registry.gitlab.com/$CI_IMAGE:latest
    - podman push -q registry.gitlab.com/$CI_IMAGE:latest

    - podman tag alertmanager-webhook-signal docker.io/$CI_IMAGE:latest
    - podman push -q docker.io/$CI_IMAGE:latest

    - podman tag alertmanager-webhook-signal docker.io/$CI_IMAGE:$CI_COMMIT_SHA
    - podman push -q docker.io/$CI_IMAGE:$CI_COMMIT_SHA

after_script:
  - podman logout registry.gitlab.com
  - podman logout docker.io