image: "quay.io/containers/buildah:v1.23.3"

variables:
  NUMBER: 0
  STORAGE_DRIVER: "vfs"
  BUILDAH_FORMAT: "docker"

before_script:
  - export VERSION=$(date -d $CI_COMMIT_TIMESTAMP +%y.%m)
  - buildah login -u $CI_USER -p $CI_TOKEN registry.gitlab.com
  - buildah login -u $GH_USER -p $GH_TOKEN docker.io

build:
  stage: build
  script:
    #- buildah pull $CI_REGISTRY_IMAGE:latest || true
    #- buildah build -f Containerfile --cache-from $CI_REGISTRY_IMAGE:latest -t registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA -t registry.gitlab.com/$CI_IMAGE:latest .
    - echo $CI_COMMIT_TIMESTAMP
    - echo $VERSION
    - date -d "$CI_COMMIT_TIMESTAMP" +%y.%m

    - buildah build -f Containerfile -t alertmanager-webhook-signal .

    - buildah tag alertmanager-webhook-signal registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA
    - buildah push -q registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA

    - buildah tag alertmanager-webhook-signal registry.gitlab.com/$CI_IMAGE:latest
    - buildah push -q registry.gitlab.com/$CI_IMAGE:latest

    - buildah tag alertmanager-webhook-signal docker.io/$CI_IMAGE:latest
    - buildah push -q docker.io/$CI_IMAGE:latest

    - buildah tag alertmanager-webhook-signal docker.io/$CI_IMAGE:$CI_COMMIT_SHA
    - buildah push -q docker.io/$CI_IMAGE:$CI_COMMIT_SHA

after_script:
  - buildah logout registry.gitlab.com
  - buildah logout docker.io