image: "buildah/buildah"

variables:
  STORAGE_DRIVER: "vfs"
  BUILDAH_FORMAT: "docker"

before_script:
  - podman login -u $CI_USER -p $CI_TOKEN registry.gitlab.com
  - podman login -u $GH_USER -p $GH_TOKEN docker.io

build:
  stage: build
  script:
    #- podman pull $CI_REGISTRY_IMAGE:latest || true
    #- podman build --cache-from $CI_REGISTRY_IMAGE:latest -t registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA -t registry.gitlab.com/$CI_IMAGE:latest .
    - podman build -t registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA -t registry.gitlab.com/$CI_IMAGE:latest -t docker.io/$CI_IMAGE:latest .
    - podman push -q registry.gitlab.com/$CI_IMAGE:$CI_COMMIT_SHA
    - podman push -q registry.gitlab.com/$CI_IMAGE:latest
    - podman push -q docker.io/$CI_IMAGE:$CI_COMMIT_SHA
    - podman push -q docker.io/$CI_IMAGE:latest

after_script:
  - podman logout registry.gitlab.com
  - podman logout docker.io