image: "quay.io/containers/buildah:v1.23.3"

variables:
  NUMBER: 0
  STORAGE_DRIVER: "vfs"
  BUILDAH_FORMAT: "docker"
  IMAGE: "schlauerlauer/alertmanager-webhook-signal"

before_script:
  - export VERSION=$(date -d $CI_COMMIT_TIMESTAMP +%y.%m).$NUMBER
  - buildah login -u $CI_USER -p $CI_TOKEN registry.gitlab.com
  - buildah login -u $GH_USER -p $GH_TOKEN docker.io

build:
  stage: build
  script:
    - buildah pull $CI_REGISTRY_IMAGE:latest || true
    - buildah build -f Containerfile -t alertmanager-webhook-signal --cache-from registry.gitlab.com/$IMAGE:latest .

    - buildah tag alertmanager-webhook-signal registry.gitlab.com/$IMAGE:$VERSION
    - buildah push -q registry.gitlab.com/$IMAGE:$VERSION

    - buildah tag alertmanager-webhook-signal registry.gitlab.com/$IMAGE:latest
    - buildah push -q registry.gitlab.com/$IMAGE:latest

    - buildah tag alertmanager-webhook-signal docker.io/$IMAGE:latest
    - buildah push -q docker.io/$IMAGE:latest

    - buildah tag alertmanager-webhook-signal docker.io/$IMAGE:$VERSION
    - buildah push -q docker.io/$IMAGE:$VERSION

after_script:
  - buildah logout registry.gitlab.com
  - buildah logout docker.io